title: Product Personalizer Developer Docs
description: A documentation for product personalizer app support executives and developers.
theme: just-the-docs

url: https://zeptoapps.github.io

aux_links:
  Doc Repository: https://zeptoapps.github.io/docs
aux_links_new_tab: false

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'A developer documentation for <a href="https://productpersonalizer.com/">Product Personalizer</a><br>Copyright &copy; 2023 by <a href="https://zeptoapps.com/">Zepto Apps</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
